# Generated by Django 5.1.5 on 2025-10-09 13:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_images/q3xcrnqej6ticrb5kuvq', max_length=255, null=True, verbose_name='image'),
        ),
    ]
